In [18]:
import pandas as pd
url = 'crabs.csv'
crabs = pd.read_csv(url)
crabs.head(30)


speies sex  index  fontallip  rearwidth  length  width  depth
0       B   M      1        8.1        6.7    16.1   19.0    7.0
1       B   M      2        8.8        7.7    18.1   20.8    7.4
2       B   M      3        9.2        7.8    19.0   22.4    7.7
3       B   M      4        9.6        7.9    20.1   23.1    8.2
4       B   M      5        9.8        8.0    20.3   23.0    8.2
5       B   M      6       10.8        9.0    23.0   26.5    9.8
6       B   M      7       11.1        9.9    23.8   27.1    9.8
7       B   M      8       11.6        9.1    24.5   28.4   10.4
8       B   M      9       11.8        9.6    24.2   27.8    9.7
9       B   M     10       11.8       10.5    25.2   29.3   10.3
10      B   M     11       12.2       10.8    27.3   31.6   10.9
11      B   M     12       12.3       11.0    26.8   31.5   11.4
12      B   M     13       12.6       10.0    27.7   31.7   11.4
13      B   M     14       12.8       10.2    27.2   31.8   10.9
14      B   M     15       12.8       10.9    27.4   31.5   11.0
15      B   M     16       12.9       11.0    26.8   30.9   11.4
16      B   M     17       13.1       10.6    28.2   32.3   11.0
17      B   M     18       13.1       10.9    28.3   32.4   11.2
18      B   M     19       13.3       11.1    27.8   32.3   11.3
19      B   M     20       13.9       11.1    29.2   33.3   12.1
20      B   M     21       14.3       11.6    31.3   35.5   12.7
21      B   M     22       14.6       11.3    31.9   36.4   13.7
22      B   M     23       15.0       10.9    31.4   36.4   13.2
23      B   M     24       15.0       11.5    32.4   37.0   13.4
24      B   M     25       15.0       11.9    32.5   37.2   13.6
25      B   M     26       15.2       12.1    32.3   36.7   13.6
26      B   M     27       15.4       11.8    33.0   37.5   13.6
27      B   M     28       15.7       12.6    35.8   40.3   14.5
28      B   M     29       15.9       12.7    34.0   38.9   14.2
29      B   M     30       16.1       11.6    33.8   39.0   14.4

In [19]:

data = crabs.replace(["F","M","B","O"],[1,0,1,0])
data


speies  sex  index  fontallip  rearwidth  length  width  depth
0         1    0      1        8.1        6.7    16.1   19.0    7.0
1         1    0      2        8.8        7.7    18.1   20.8    7.4
2         1    0      3        9.2        7.8    19.0   22.4    7.7
3         1    0      4        9.6        7.9    20.1   23.1    8.2
4         1    0      5        9.8        8.0    20.3   23.0    8.2
..      ...  ...    ...        ...        ...     ...    ...    ...
195       0    1     46       21.4       18.0    41.2   46.2   18.7
196       0    1     47       21.7       17.1    41.7   47.2   19.6
197       0    1     48       21.9       17.2    42.6   47.4   19.5
198       0    1     49       22.5       17.2    43.0   48.7   19.8
199       0    1     50       23.1       20.2    46.2   52.5   21.1

[200 rows x 8 columns]

In [52]:
from sklearn.linear_model import Perceptron
from sklearn import datasets
from sklearn.model_selection import train_test_split # chia ra 7 phan train, 3 phan test
from sklearn.metrics import accuracy_score
import numpy as np

from sklearn.preprocessing import StandardScaler
#scale các dữ liệu không đều theo 1 tỉ lệ từ 0 -> 1


X1 = data['fontallip'].values
X2 = data['sex'].values
X3 = data['index'].values
X4 = data['rearwidth'].values
X5 = data['length'].values
X6 = data['width'].values
X7 = data['depth'].values

y = data['speies'].values

col_X1 = X1.reshape(-1,1)
col_X2 = X2.reshape(-1,1)
col_X3 = X3.reshape(-1,1)
col_X4 = X4.reshape(-1,1)
col_X5 = X5.reshape(-1,1)
col_X6 = X6.reshape(-1,1)
col_X7 = X7.reshape(-1,1)

X = np.hstack((col_X1,col_X2,col_X3,col_X4,col_X5,col_X6,col_X7))

print("Number of columns:", col_X1.shape[0])

print(X[:7][:7])

print(y[:20])


Number of columns: 200
[[ 8.1  0.   1.   6.7 16.1 19.   7. ]
 [ 8.8  0.   2.   7.7 18.1 20.8  7.4]
 [ 9.2  0.   3.   7.8 19.  22.4  7.7]
 [ 9.6  0.   4.   7.9 20.1 23.1  8.2]
 [ 9.8  0.   5.   8.  20.3 23.   8.2]
 [10.8  0.   6.   9.  23.  26.5  9.8]
 [11.1  0.   7.   9.9 23.8 27.1  9.8]]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [54]:
X_train, X_test,y_train, y_test = train_test_split(X,y,test_size = 0.3) #test =0.3, train = 0.7

sc =  StandardScaler()
sc.fit(X)

X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)


print(X_train_std[:5],X_train[:5])

print(y[:5])

[[-0.85556722  1.         -1.4898617  -0.48248889 -1.00061071 -1.05886839
  -0.74073541]
 [ 0.54982312  1.          1.62845348  1.54330218  0.91456847  1.02970478
   0.86924078]
 [ 0.32037164  1.         -0.4504233   0.60832168  0.02738988  0.07456461
   0.19597801]
 [-0.68347861 -1.         -1.21267813 -0.6772765  -0.70488451 -0.76595874
  -0.53582935]
 [-0.42534569 -1.         -0.86619866 -0.8720641  -0.42324052 -0.61313631
  -0.2723787 ]] [[12.6  1.   4.  11.5 25.  28.1 11.5]
 [17.5  1.  49.  16.7 38.6 44.5 17. ]
 [16.7  1.  19.  14.3 32.3 37.  14.7]
 [13.2  0.   8.  11.  27.1 30.4 12.2]
 [14.1  0.  13.  10.5 29.1 31.6 13.1]]
[1 1 1 1 1]


In [56]:
model = Perceptron(max_iter= 40, eta0 = 0.1, random_state = 0)
# số lần học: max_iter 
# eta0 :  tốc độ học  giá trị từ 0 đến 1
# random_state : trạng thái giá trị ngẫu nhiên

model.fit(X_train_std, y_train)
y_pred = model.predict(X_test_std)
print(y_pred)
print(y_test)
print('Độ chính xác mô hình: ', accuracy_score(y_test, y_pred))

[1 0 1 0 1 0 1 1 1 1 0 0 1 0 1 0 0 0 1 0 1 1 0 1 1 1 1 0 1 0 0 1 0 1 0 0 0
 0 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 1 0 0 0 1 1]
[1 0 1 0 1 0 0 1 1 1 0 0 0 0 1 0 0 0 1 0 1 1 0 1 1 1 1 0 1 0 0 1 0 1 0 0 0
 0 0 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 1 0 0 0 1 1]
Độ chính xác mô hình:  0.95


In [57]:
model = Perceptron(max_iter= 1000, eta0 = 0.3, random_state = 0)
# số lần học: max_iter 
# eta0 :  tốc độ học  giá trị từ 0 đến 1
# random_state : trạng thái giá trị ngẫu nhiên

model.fit(X_train_std, y_train)
y_pred = model.predict(X_test_std)
print(y_pred)
print(y_test)
print('Độ chính xác mô hình: ', accuracy_score(y_test, y_pred))

[1 0 1 0 1 0 1 1 1 1 0 0 1 0 1 0 0 0 1 0 1 1 0 1 1 1 1 0 1 0 0 1 0 1 0 0 0
 0 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 1 0 0 0 1 1]
[1 0 1 0 1 0 0 1 1 1 0 0 0 0 1 0 0 0 1 0 1 1 0 1 1 1 1 0 1 0 0 1 0 1 0 0 0
 0 0 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 1 0 0 0 1 1]
Độ chính xác mô hình:  0.95
